title = "Soundgasbord"
author = "Krishna BM"
shortname = "soundgasbord"
version = "1.0.0"
support_email = "krishnabmahadevan@gmail.com"
copyright_message = "Copyright © 2023"
icon = "assets/icon.png"
